# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

dockers:
  - goos: linux
    goarch: amd64
    binaries:
    - retag
    image_templates:
    - "hugoshaka/retag:scratch"
    - "hugoshaka/retag:scratch-{{ .Tag }}"
    - "hugoshaka/retag:scratch-v{{ .Major }}"
    skip_push: true
    dockerfile: Dockerfile.scratch
  - goos: linux
    goarch: amd64
    binaries:
    - retag
    image_templates:
    - "hugoshaka/retag:debian"
    - "hugoshaka/retag:debian-{{ .Tag }}"
    - "hugoshaka/retag:debian-v{{ .Major }}"
    skip_push: true
    dockerfile: Dockerfile.debian